default:

  http_metas:
    content-type: text/html

  stylesheets:
    - layout
    - typography
    - navigation

  javascripts:     # we don't need any JS right now

  has_layout:      true
  layout:          layout 